apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: rabbitmq
  template:
    metadata:
      labels:
        component: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:management
          ports:
          - name: port1
            containerPort: 5672
          - name: port2
            containerPort: 15672
          env:
          - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
            value: -rabbitmq_management path_prefix "/rabbitmq"
---
apiVersion: v1
kind: Service
metadata:
 name: rabbitmq-cluster-ip-service
spec:
 type: ClusterIP
 ports:
   - name: port1
     port: 5672
     targetPort: 5672
   - name: port2
     port: 15672
     targetPort: 15672
 selector:
   component: rabbitmq
            
